import Mathlib

namespace Hilbert17thProblem

open scoped BigOperators

noncomputable section

variable {R : Type*} [CommRing R]

/-- Membership normal form for the subsemiring generated by a preordering `P` and `a`. -/
theorem mem_closure_insert_preordering
    (P : RingPreordering R) (a : R) {x : R}
    (hx : x ∈ Subsemiring.closure (insert a (P : Set R))) :
    ∃ y z, (y : R) ∈ P ∧ z ∈ P ∧ x = y + a * z := by
  induction hx using Subsemiring.closure_induction with
  | mem x hx =>
      rcases hx with (rfl | hx)
      · exact ⟨0, 1, by simp, by simp, by simp⟩
      · exact ⟨x, 0, hx, by simp, by simp⟩
  | zero => exact ⟨0, 0, by simp, by simp, by simp⟩
  | one => exact ⟨1, 0, by simp, by simp, by simp⟩
  | add x y _ _ hx hy =>
      rcases hx with ⟨x₁, x₂, hx₁, hx₂, rfl⟩
      rcases hy with ⟨y₁, y₂, hy₁, hy₂, rfl⟩
      exact ⟨x₁ + y₁, x₂ + y₂, P.add_mem hx₁ hy₁, P.add_mem hx₂ hy₂, by ring⟩
  | mul x y _ _ hx hy =>
      rcases hx with ⟨x₁, x₂, hx₁, hx₂, rfl⟩
      rcases hy with ⟨y₁, y₂, hy₁, hy₂, rfl⟩
      exact ⟨x₁ * y₁ + (a * a) * (x₂ * y₂),
        x₁ * y₂ + y₁ * x₂,
        P.add_mem (P.mul_mem hx₁ hy₁)
        (P.mul_mem (P.mul_self_mem a) (P.mul_mem hx₂ hy₂)),
        P.add_mem (P.mul_mem hx₁ hy₂) (P.mul_mem hy₁ hx₂), by ring⟩


/-- The generated subsemiring is a preordering provided `-1` is absent. -/
def preorderingOfClosure
    (P : RingPreordering R) (a : R)
    (h : -1 ∉ Subsemiring.closure (insert a (P : Set R))) :
    RingPreordering R where
  toSubsemiring := Subsemiring.closure (insert a (P : Set R))
  mem_of_isSquare' {x hx} := by
    rcases hx with ⟨y, rfl⟩
    exact Subsemiring.subset_closure
      (Set.mem_insert_of_mem _ (P.mul_self_mem y))
  neg_one_notMem' := h

@[simp]
theorem mem_preorderingOfClosure {P : RingPreordering R} {a x : R}
    {h : -1 ∉ Subsemiring.closure (insert a (P : Set R))} :
    x ∈ preorderingOfClosure P a h ↔
      x ∈ Subsemiring.closure (insert a (P : Set R)) := Iff.rfl

theorem le_preorderingOfClosure (P : RingPreordering R) (a : R)
    (h : -1 ∉ Subsemiring.closure (insert a (P : Set R))) : P ≤ preorderingOfClosure P a h := by
  intro x hx
  exact Subsemiring.subset_closure (Set.mem_insert_of_mem _ hx)

theorem mem_preorderingOfClosure_insert (P : RingPreordering R) (a : R)
    (h : -1 ∉ Subsemiring.closure (insert a (P : Set R))) :
    a ∈ preorderingOfClosure P a h :=
  Subsemiring.subset_closure (Set.mem_insert _ _)

/-- On a field, adjoining an element whose negative is not positive cannot create `-1`. -/
theorem neg_one_notMem_closure_insert_of_neg_notMem
    {F : Type*} [Field F] (P : RingPreordering F) {a : F}
    (ha : -a ∉ P) :
    -1 ∉ Subsemiring.closure (insert a (P : Set F)) := by
  intro hc
  obtain ⟨y, z, hy, hz, hx⟩ := mem_closure_insert_preordering P a hc
  have hz0 : z ≠ 0 := by
    rintro rfl
    exact P.neg_one_notMem (by simp_all)
  have hzinv : z⁻¹ ∈ P :=
    RingPreordering.inv_mem (show z ∈ P from hz)
  have hprod : y * z⁻¹ + z⁻¹ ∈ P :=
    P.add_mem (P.mul_mem hy hzinv) hzinv
  have hkey : -a = y * z⁻¹ + z⁻¹ := by
    field_simp
    linear_combination hx
  exact ha (hkey ▸ hprod)

/-- If `- (x*y)` is nonnegative in a preordering, adjoining either factor cannot make `-1`
nonnegative in both generated preorderings. -/
theorem neg_one_notMem_closure_insert_or
    (P : RingPreordering R) {x y : R} (hxy : -(x * y) ∈ P) :
    -1 ∉ Subsemiring.closure (insert x (P : Set R)) ∨
      -1 ∉ Subsemiring.closure (insert y (P : Set R)) := by
  by_contra hcon
  have hx : -1 ∈ Subsemiring.closure (insert x (P : Set R)) := by
    by_contra hc
    exact hcon (Or.inl hc)
  have hy : -1 ∈ Subsemiring.closure (insert y (P : Set R)) := by
    by_contra hc
    exact hcon (Or.inr hc)
  clear hcon
  rcases mem_closure_insert_preordering P x hx with ⟨x₁, x₂, hx₁, hx₂, hex⟩
  rcases mem_closure_insert_preordering P y hy with ⟨y₁, y₂, hy₁, hy₂, hey⟩
  apply P.neg_one_notMem
  have key : -1 = -(x*y) * x₂ * y₂ + x₁ + y₁ + x₁ * y₁ := by
    linear_combination (y₁ + 1) * hex - 1 * x * x₂ * hey
  rw [key]
  have hprod : -(x*y) * x₂ * y₂ ∈ P :=
    P.mul_mem (P.mul_mem hxy hx₂) hy₂
  have hrest : x₁ + y₁ + x₁ * y₁ ∈ P :=
    P.add_mem (P.add_mem hx₁ hy₁) (P.mul_mem hx₁ hy₁)
  have : -(x*y) * x₂ * y₂ + (x₁ + y₁ + x₁ * y₁) ∈ P :=
    P.add_mem hprod hrest
  ring_nf at this ⊢
  exact this

theorem exists_le_preordering_and_mem_or_mem
    (P : RingPreordering R) {x y : R} (hxy : -(x * y) ∈ P) :
    ∃ Q : RingPreordering R, P ≤ Q ∧ (x ∈ Q ∨ y ∈ Q) := by
  rcases neg_one_notMem_closure_insert_or P hxy with h | h
  · exact ⟨preorderingOfClosure P x h, le_preorderingOfClosure P x h,
      Or.inl (mem_preorderingOfClosure_insert P x h)⟩
  · exact ⟨preorderingOfClosure P y h, le_preorderingOfClosure P y h,
      Or.inr (mem_preorderingOfClosure_insert P y h)⟩

/-- Construct a bundled preordering whose carrier is a specified subsemiring. -/
def preorderingOfSubsemiring
    (S : Subsemiring R)
    (hsq : ∀ x, IsSquare x → x ∈ S)
    (hne : -1 ∉ S) : RingPreordering R where
  toSubsemiring := S
  mem_of_isSquare' := fun hx => hsq _ hx
  neg_one_notMem' := hne

@[simp]
theorem mem_preorderingOfSubsemiring
    {S : Subsemiring R} {hsq hne x} :
    x ∈ preorderingOfSubsemiring S hsq hne ↔ x ∈ S := Iff.rfl

theorem sSup_preordering
    {C : Set (RingPreordering R)} (hne : C.Nonempty)
    (hdir : DirectedOn (· ≤ ·) C) :
    ∃ Q : RingPreordering R, ∀ P ∈ C, P ≤ Q := by
  have hmem : ∀ x ∈ sSup ((fun P => P.toSubsemiring) '' C),
      ∃ P ∈ C, x ∈ P := by
    intro x hx
    have himage : ((fun P => P.toSubsemiring) '' C).Nonempty :=
      Set.Nonempty.image (fun P => P.toSubsemiring) hne
    have hdirS : DirectedOn (· ≤ ·) ((fun P => P.toSubsemiring) '' C) := by
      rintro S₁ ⟨P₁, hP₁, rfl⟩ S₂ ⟨P₂, hP₂, rfl⟩
      rcases hdir P₁ hP₁ P₂ hP₂ with ⟨Q, hQ₁, hQ₂, hQ₃⟩
      exact ⟨Q.toSubsemiring, ⟨Q, hQ₁, rfl⟩, hQ₂, hQ₃⟩
    simpa using (Subsemiring.mem_sSup_of_directedOn himage hdirS).mp hx
  refine ⟨preorderingOfSubsemiring (sSup ((fun P => P.toSubsemiring) '' C))
    (fun x hx => ?_) (fun h => ?_), fun P hP x hx => ?_⟩
  · rcases hne with ⟨Z, hZ⟩
    have hxs : x ∈ Z := Z.mem_of_isSquare hx
    have hxsup : x ∈ sSup ((fun P => P.toSubsemiring) '' C) :=
      (le_sSup (Set.mem_image_of_mem (fun P => P.toSubsemiring) hZ)) hxs
    exact hxsup
  · rcases hne with ⟨Q, hQ⟩
    rcases hmem (-1) h with ⟨Z, hZ, hmem1⟩
    exact Z.neg_one_notMem hmem1
  · have hxsup : x ∈ sSup ((fun Q => Q.toSubsemiring) '' C) :=
      (le_sSup (Set.mem_image_of_mem (fun Q => Q.toSubsemiring) hP)) hx
    exact hxsup

/-- Every preordering is bounded by a maximal preordering above it. -/
theorem exists_maximal_preordering
    (P : RingPreordering R) :
    ∃ Q : RingPreordering R, P ≤ Q ∧ Maximal (fun Q => P ≤ Q) Q := by
  have hzorn := zorn_le_nonempty₀ {Q : RingPreordering R | P ≤ Q}
    (fun C hC hchain y hy => by
      have hne : C.Nonempty := ⟨y, hy⟩
      have hdir : DirectedOn (· ≤ ·) C := hchain.directedOn
      rcases sSup_preordering hne hdir with ⟨Q, hQ⟩
      exact ⟨Q, le_trans (hC hy) (hQ y hy), fun z hz => hQ z hz⟩)
    P (Set.mem_setOf_eq.mpr le_rfl)
  exact ⟨hzorn.choose, hzorn.choose_spec.1, hzorn.choose_spec.2⟩

/-- A preordering maximal above `P` is an ordering. -/
theorem isOrdering_of_maximal_preordering
    {P O : RingPreordering R} (hPO : P ≤ O)
    (hmax : Maximal (fun Q => P ≤ Q) O) : O.IsOrdering := by
  rw [RingPreordering.isOrdering_iff]
  intro a b hab
  rcases exists_le_preordering_and_mem_or_mem O hab with ⟨Q, hOQ, hab⟩
  rcases hab with ha | hb
  · exact Or.inl ((hmax.2 (le_trans hPO hOQ) hOQ) ha)
  · exact Or.inr ((hmax.2 (le_trans hPO hOQ) hOQ) hb)



instance ringConeClass {F : Type*} [Field F] :
    RingConeClass (RingPreordering F) F where
  zero_mem := fun {_} => Subsemiring.zero_mem _
  one_mem := fun {_} => Subsemiring.one_mem _
  add_mem := fun ha hb => Subsemiring.add_mem _ ha hb
  mul_mem := fun ha hb => Subsemiring.mul_mem _ ha hb
  eq_zero_of_mem_of_neg_mem := fun ha hb =>
    RingPreordering.eq_zero_of_mem_of_neg_mem ha hb

open scoped Classical in
/-- Construct the linear order whose positive cone is a field ordering. -/
noncomputable def linearOrderOfOrdering {F : Type*} [Field F]
    (O : RingPreordering F) [O.IsOrdering] : LinearOrder F :=
  LinearOrder.mkOfAddGroupCone O

theorem order_mem_iff {F : Type*} [Field F] (O : RingPreordering F) [O.IsOrdering]
    (a b : F) : @LE.le F (linearOrderOfOrdering O).toLE a b ↔ b - a ∈ O := by
  constructor
  · intro h
    simpa [linearOrderOfOrdering] using
      (PartialOrder.mkOfAddGroupCone_le_iff (C := O) (a := a) (b := b)).mp h
  · intro h
    simpa [linearOrderOfOrdering] using
      (PartialOrder.mkOfAddGroupCone_le_iff (C := O) (a := a) (b := b)).mpr h

open scoped Classical in
/-- The linear order induced by a field ordering makes the field strictly ordered. -/
theorem isStrictOrderedRing_ofOrdering {F : Type*} [Field F]
    (O : RingPreordering F) [O.IsOrdering] :
    letI : LinearOrder F := linearOrderOfOrdering O
    IsStrictOrderedRing F := by
  letI inst : LinearOrder F := linearOrderOfOrdering O
  haveI : IsOrderedAddMonoid F := IsOrderedAddMonoid.mkOfCone O
  haveI : ZeroLEOneClass F :=
    ⟨order_mem_iff O 0 1 |>.mpr (by simp)⟩
  apply IsStrictOrderedRing.of_mul_pos
  intro x y hx hy
  have hx' : x ∈ O := by
    simpa [sub_eq_zero] using order_mem_iff O 0 x |>.mp hx.le
  have hy' : y ∈ O := by
    simpa [sub_eq_zero] using order_mem_iff O 0 y |>.mp hy.le
  have hxy : x * y ∈ O := O.mul_mem hx' hy'
  have hle : 0 ≤ x * y := by
    simpa [sub_eq_zero] using
      (order_mem_iff O 0 (x * y)).mpr (by simpa using hxy)
  rcases eq_or_ne (x * y) 0 with h0 | h0
  · exact absurd h0 (by
      intro h0
      rcases mul_eq_zero.mp h0 with hx0 | hy0
      · exact lt_irrefl 0 (hx0 ▸ hx)
      · exact lt_irrefl 0 (hy0 ▸ hy))
  · exact hle.lt_of_ne (Ne.symm h0)

/-- Every preordering on a field extends to a maximal preordering containing `a` whenever
`-a ∉ P`. The maximality is among preorderings above the generated preordering. -/
theorem exists_maximal_preordering_and_mem
    {F : Type*} [Field F] (P : RingPreordering F) {a : F}
    (ha : -a ∉ P) :
    ∃ O : RingPreordering F, P ≤ O ∧
      Maximal (fun Q => preorderingOfClosure P a
        (neg_one_notMem_closure_insert_of_neg_notMem P ha) ≤ Q) O ∧ a ∈ O := by
  have h := neg_one_notMem_closure_insert_of_neg_notMem P ha
  obtain ⟨Q, hPQ, hQmax⟩ := exists_maximal_preordering (preorderingOfClosure P a h)
  exact ⟨Q, le_trans (le_preorderingOfClosure P a h) hPQ, hQmax,
    hPQ (mem_preorderingOfClosure_insert P a h)⟩

/-- Every preordering on a field extends to an ordering containing `a` whenever `-a ∉ P`. -/
theorem exists_isOrdering_and_mem
    {F : Type*} [Field F] (P : RingPreordering F) {a : F}
    (ha : -a ∉ P) :
    ∃ O : RingPreordering F, P ≤ O ∧ O.IsOrdering ∧ a ∈ O := by
  have h := neg_one_notMem_closure_insert_of_neg_notMem P ha
  obtain ⟨Q, hPQ, hQmax⟩ := exists_maximal_preordering (preorderingOfClosure P a h)
  exact ⟨Q, le_trans (le_preorderingOfClosure P a h) hPQ,
    isOrdering_of_maximal_preordering hPQ hQmax,
    hPQ (mem_preorderingOfClosure_insert P a h)⟩

open scoped Classical in
/-- The canonical preordering of sums of squares in a semireal field. -/
noncomputable def sumSqPreordering {F : Type*} [Field F] [IsSemireal F] :
    RingPreordering F :=
  RingPreordering.mk' {x | IsSumSq x}
    (by intro x y hx hy; exact hx.add hy)
    (by intro x y hx hy; exact hx.mul hy)
    (by intro x; exact IsSumSq.mul_self x)
    (by intro h; exact absurd h (isSemireal_iff_not_isSumSq_neg_one.mp inferInstance))

/-- If `a` is not a sum of squares, there is a field ordering in which `-a` is positive. -/
theorem exists_isOrdering_and_neg_mem {F : Type*} [Field F] [IsSemireal F]
    {a : F} (ha : a ∉ sumSqPreordering) :
    ∃ O : RingPreordering F, O.IsOrdering ∧ -a ∈ O := by
  have hn : -(-a) ∉ sumSqPreordering := by simpa [neg_neg] using ha
  obtain ⟨O, _, hO, hmem⟩ := exists_isOrdering_and_mem sumSqPreordering hn
  exact ⟨O, hO, hmem⟩

end

open scoped Classical in
/-- A nonzero real multivariate polynomial has a real point where it does not vanish. -/
theorem exists_eval_ne_zero {n : ℕ} {p : MvPolynomial (Fin n) ℝ} (hp : p ≠ 0) :
    ∃ x : Fin n → ℝ, MvPolynomial.eval x p ≠ 0 := by
  by_contra hcon
  have hall : ∀ x : Fin n → ℝ, MvPolynomial.eval x p = 0 := by
    intro x
    by_contra hx
    exact hcon ⟨x, hx⟩
  exact hp (MvPolynomial.funext (q := 0) hall)

section FractionRingField

/-- A fraction in `FractionRing (MvPolynomial (Fin n) ℝ)` can be represented using a
polynomial numerator and a nonzero polynomial denominator. -/
theorem denom_mvFraction {n : ℕ} (x : FractionRing (MvPolynomial (Fin n) ℝ)) :
    ∃ a b : MvPolynomial (Fin n) ℝ, b ≠ 0 ∧
      x * algebraMap (MvPolynomial (Fin n) ℝ)
          (FractionRing (MvPolynomial (Fin n) ℝ)) b =
        algebraMap (MvPolynomial (Fin n) ℝ)
          (FractionRing (MvPolynomial (Fin n) ℝ)) a := by
  obtain ⟨p, hp⟩ :=
    IsLocalization.surj (nonZeroDivisors (MvPolynomial (Fin n) ℝ)) x
  exact ⟨p.1, p.2.1, mem_nonZeroDivisors_iff_ne_zero.mp p.2.2, hp⟩

/-- Convert the inductively defined `IsSumSq` predicate to an explicitly indexed finite sum. -/
theorem isSumSq_iff_exists_fin {R : Type*} [CommSemiring R] {x : R} :
    IsSumSq x ↔ ∃ m : ℕ, ∃ f : Fin m → R, x = ∑ i : Fin m, (f i) ^ 2 := by
  constructor
  · intro h
    induction h using IsSumSq.rec' with
    | zero => exact ⟨0, Fin.elim0, by simp⟩
    | @sq_add a s ht hs ih =>
        obtain ⟨a, rfl⟩ := ht
        obtain ⟨m, f, hf⟩ := ih
        refine ⟨m + 1, Fin.cases a f, ?_⟩
        rw [Fin.sum_univ_succ]
        simp [pow_two, hf]
  · rintro ⟨m, f, rfl⟩
    exact IsSumSq.sum_sq Finset.univ f

/-- The rational function field in finitely many real variables is formally real:
`-1` is not a sum of squares. -/
theorem isSemireal_mvFractionRing (n : ℕ) :
    IsSemireal (FractionRing (MvPolynomial (Fin n) ℝ)) := by
  refine isSemireal_iff_not_isSumSq_neg_one.mpr ?_
  intro hsum
  obtain ⟨m, f, hf⟩ := (isSumSq_iff_exists_fin).mp hsum
  choose a b hb hrel using fun i : Fin m =>
    denom_mvFraction (n := n) (f i)
  set D : MvPolynomial (Fin n) ℝ := ∏ i, b i with hD
  have hD0 : D ≠ 0 := by
    intro h0
    obtain ⟨i, _, hi0⟩ := Finset.prod_eq_zero_iff.mp h0
    exact hb i hi0
  set c : Fin m → MvPolynomial (Fin n) ℝ :=
    fun i => ∏ j ∈ Finset.univ.erase i, b j with hc
  have hcD : ∀ i : Fin m, c i * b i = D := by
    intro i
    calc c i * b i = (∏ j ∈ Finset.univ.erase i, b j) * b i := rfl
      _ = D := by
          rw [hD, Finset.prod_erase_mul Finset.univ b (Finset.mem_univ i)]
  have hclear : algebraMap (MvPolynomial (Fin n) ℝ)
        (FractionRing (MvPolynomial (Fin n) ℝ)) (-(D ^ 2)) =
      algebraMap (MvPolynomial (Fin n) ℝ)
        (FractionRing (MvPolynomial (Fin n) ℝ)) (∑ i, (a i * c i) ^ 2) := by
    refine (IsFractionRing.injective (MvPolynomial (Fin n) ℝ)
      (FractionRing (MvPolynomial (Fin n) ℝ))).eq_iff.mpr ?_
    have hbmono : ∀ i : Fin m, algebraMap (MvPolynomial (Fin n) ℝ)
        (FractionRing (MvPolynomial (Fin n) ℝ)) (b i) ≠ 0 := by
      intro i hmap
      exact hb i (IsFractionRing.injective (MvPolynomial (Fin n) ℝ)
        (FractionRing (MvPolynomial (Fin n) ℝ)) (by simpa using hmap))
    have hcmul : ∀ i : Fin m,
        algebraMap (MvPolynomial (Fin n) ℝ)
          (FractionRing (MvPolynomial (Fin n) ℝ)) (c i) *
        algebraMap (MvPolynomial (Fin n) ℝ)
          (FractionRing (MvPolynomial (Fin n) ℝ)) (b i) =
        algebraMap (MvPolynomial (Fin n) ℝ)
          (FractionRing (MvPolynomial (Fin n) ℝ)) D := by
      intro i
      rw [← map_mul, hcD i]
    have key : ∀ i : Fin m,
        algebraMap (MvPolynomial (Fin n) ℝ)
          (FractionRing (MvPolynomial (Fin n) ℝ)) D ^ 2 * f i ^ 2 =
        algebraMap (MvPolynomial (Fin n) ℝ)
          (FractionRing (MvPolynomial (Fin n) ℝ)) ((a i * c i) ^ 2) := by
      intro i
      rw [show algebraMap (MvPolynomial (Fin n) ℝ)
            (FractionRing (MvPolynomial (Fin n) ℝ)) D =
          algebraMap (MvPolynomial (Fin n) ℝ)
            (FractionRing (MvPolynomial (Fin n) ℝ)) (c i) *
          algebraMap (MvPolynomial (Fin n) ℝ)
            (FractionRing (MvPolynomial (Fin n) ℝ)) (b i) from (hcmul i).symm,
        show algebraMap (MvPolynomial (Fin n) ℝ)
            (FractionRing (MvPolynomial (Fin n) ℝ)) ((a i * c i) ^ 2) =
          algebraMap (MvPolynomial (Fin n) ℝ)
            (FractionRing (MvPolynomial (Fin n) ℝ)) (a i ^ 2) *
          algebraMap (MvPolynomial (Fin n) ℝ)
            (FractionRing (MvPolynomial (Fin n) ℝ)) (c i ^ 2) by
          rw [map_pow, map_mul, map_pow, map_pow]
          ring]
      rw [map_pow, map_pow, ← hrel i]
      ring_nf
    have key_sum :
        algebraMap (MvPolynomial (Fin n) ℝ)
          (FractionRing (MvPolynomial (Fin n) ℝ)) D ^ 2 * ∑ i, f i ^ 2 =
      algebraMap (MvPolynomial (Fin n) ℝ)
        (FractionRing (MvPolynomial (Fin n) ℝ)) (∑ i, (a i * c i) ^ 2) := by
      rw [Finset.mul_sum, map_sum]
      exact Finset.sum_congr rfl (fun i _ => key i)
    have h1 : algebraMap (MvPolynomial (Fin n) ℝ)
        (FractionRing (MvPolynomial (Fin n) ℝ)) (-(D ^ 2)) =
      algebraMap (MvPolynomial (Fin n) ℝ)
        (FractionRing (MvPolynomial (Fin n) ℝ)) (∑ i, (a i * c i) ^ 2) := by
      rw [map_neg, map_pow]
      have h2 : -((algebraMap (MvPolynomial (Fin n) ℝ)
            (FractionRing (MvPolynomial (Fin n) ℝ)) D)^2) =
          (algebraMap (MvPolynomial (Fin n) ℝ)
            (FractionRing (MvPolynomial (Fin n) ℝ)) D)^2 * ∑ i, f i ^ 2 := by
        have hminus : (-1 : FractionRing (MvPolynomial (Fin n) ℝ)) = ∑ i, f i ^ 2 := hf
        calc -((algebraMap (MvPolynomial (Fin n) ℝ)
              (FractionRing (MvPolynomial (Fin n) ℝ)) D)^2) =
            (algebraMap (MvPolynomial (Fin n) ℝ)
              (FractionRing (MvPolynomial (Fin n) ℝ)) D)^2 *
            (-1 : FractionRing (MvPolynomial (Fin n) ℝ)) := by ring
          _ = (algebraMap (MvPolynomial (Fin n) ℝ)
              (FractionRing (MvPolynomial (Fin n) ℝ)) D)^2 * ∑ i, f i ^ 2 := by
              rw [hminus]
      rw [h2, key_sum]
    exact IsFractionRing.injective (MvPolynomial (Fin n) ℝ)
      (FractionRing (MvPolynomial (Fin n) ℝ)) h1
  have hA : -(D ^ 2) = ∑ i, (a i * c i) ^ 2 := by
    exact IsFractionRing.injective (MvPolynomial (Fin n) ℝ)
      (FractionRing (MvPolynomial (Fin n) ℝ))
      (show algebraMap (MvPolynomial (Fin n) ℝ)
        (FractionRing (MvPolynomial (Fin n) ℝ)) (-(D^2)) =
      algebraMap (MvPolynomial (Fin n) ℝ)
        (FractionRing (MvPolynomial (Fin n) ℝ)) (∑ i, (a i * c i)^2) from hclear)
  obtain ⟨x, hx⟩ := exists_eval_ne_zero (p := D) hD0
  have hev : (-1 : ℝ) * (MvPolynomial.eval x D) ^ 2 =
      ∑ i, (MvPolynomial.eval x (a i * c i)) ^ 2 := by
    have h1 : (MvPolynomial.eval x) (-(D : MvPolynomial (Fin n) ℝ)^2) =
        (MvPolynomial.eval x) (∑ i, (a i * c i)^2) := by rw [hA]
    simpa [sq_abs] using h1
  have hnonneg : 0 ≤ ∑ i, (MvPolynomial.eval x (a i * c i)) ^ 2 :=
    Finset.sum_nonneg (fun i _ => sq_nonneg _)
  have hneg : (-1 : ℝ) * (MvPolynomial.eval x D) ^ 2 < 0 := by
    apply mul_neg_of_neg_of_pos
    · norm_num
    · exact sq_pos_of_ne_zero hx
  linarith

end FractionRingField


section RealClosed

open Filter Polynomial Set in
/-- Every real polynomial of odd degree has a real root, by the intermediate value theorem. -/
theorem exists_isRoot_of_odd_natDegree_real {f : ℝ[X]} (hodd : Odd f.natDegree) :
    ∃ x : ℝ, f.IsRoot x := by
  have hpos : 0 < f.natDegree := by
    obtain ⟨k, hk⟩ := hodd
    omega
  have hdegree : 0 < f.degree := natDegree_pos_iff_degree_pos.mp hpos
  have hne : f ≠ 0 := f.ne_zero_of_natDegree_gt hpos
  have hlead0 : f.leadingCoeff ≠ 0 := f.leadingCoeff_ne_zero.mpr hne
  have hc : Continuous (fun x : ℝ => f.eval x) := f.continuous
  have hcompdeg : (f.comp (-X)).degree = f.degree := degree_comp_neg_X
  have hcomplead : (f.comp (-X)).leadingCoeff = (-1) ^ f.natDegree * f.leadingCoeff :=
    comp_neg_X_leadingCoeff_eq f
  rw [Odd.neg_one_pow hodd] at hcomplead
  rcases lt_or_ge f.leadingCoeff 0 with hlead | hlead
  · -- At `+∞` the polynomial is negative, while at `-∞` it is positive.
    have hright : Tendsto (fun x : ℝ => f.eval x) atTop atBot :=
      f.tendsto_atBot_of_leadingCoeff_nonpos hdegree hlead.le
    have hleft : Tendsto (fun x : ℝ => f.eval x) atBot atTop := by
      have hbase : Tendsto (fun x : ℝ => (f.comp (-X)).eval x) atTop atTop :=
        (f.comp (-X)).tendsto_atTop_of_leadingCoeff_nonneg (hcompdeg ▸ hdegree)
          (by rw [hcomplead]; simpa using le_of_lt (neg_pos.mpr hlead))
      have hcomp := hbase.comp tendsto_neg_atBot_atTop
      convert hcomp using 1
      funext x
      simp [eval_comp]
    obtain ⟨B, hB⟩ := eventually_atBot.1 (hleft.eventually_gt_atTop 0)
    obtain ⟨A, hA⟩ := eventually_atTop.1 (hright.eventually_lt_atBot 0)
    set C := max (A + 1) (B + 1) with hC
    have hBC : B < C := by
      rw [hC]
      by_cases hcase : A + 1 ≤ B + 1
      · rw [max_eq_right hcase]; linarith
      · rw [max_eq_left (by linarith)]; linarith
    have hAC : A < C := by
      rw [hC]
      by_cases hcase : A + 1 ≤ B + 1
      · rw [max_eq_right hcase]; linarith
      · rw [max_eq_left (by linarith)]; linarith
    have hB0 : 0 < f.eval B := hB B (by linarith)
    have hC0 : f.eval C < 0 := hA C hAC.le
    have hmem : (0:ℝ) ∈ Icc (f.eval C) (f.eval B) := by
      constructor <;> [exact le_of_lt hC0; exact le_of_lt hB0]
    have him := intermediate_value_Icc' hBC.le hc.continuousOn hmem
    obtain ⟨c, _, hceq⟩ := him
    exact ⟨c, hceq⟩
  · -- At `+∞` the polynomial is positive, while at `-∞` it is negative.
    have hright : Tendsto (fun x : ℝ => f.eval x) atTop atTop :=
      f.tendsto_atTop_of_leadingCoeff_nonneg hdegree hlead
    have hleft : Tendsto (fun x : ℝ => f.eval x) atBot atBot := by
      have hbase : Tendsto (fun x : ℝ => (f.comp (-X)).eval x) atTop atBot :=
        (f.comp (-X)).tendsto_atBot_of_leadingCoeff_nonpos (hcompdeg ▸ hdegree)
          (by rw [hcomplead]
              simpa using le_of_lt (neg_neg_iff_pos.mpr (lt_of_le_of_ne hlead
                (fun h => hlead0 h.symm))))
      have hcomp := hbase.comp tendsto_neg_atBot_atTop
      convert hcomp using 1
      funext x
      simp [eval_comp]
    obtain ⟨B, hB⟩ := eventually_atBot.1 (hleft.eventually_lt_atBot 0)
    obtain ⟨A, hA⟩ := eventually_atTop.1 (hright.eventually_gt_atTop 0)
    set C := max (A + 1) (B + 1) with hC
    have hBC : B < C := by
      rw [hC]
      by_cases hcase : A + 1 ≤ B + 1
      · rw [max_eq_right hcase]; linarith
      · rw [max_eq_left (by linarith)]; linarith
    have hAC : A < C := by
      rw [hC]
      by_cases hcase : A + 1 ≤ B + 1
      · rw [max_eq_right hcase]; linarith
      · rw [max_eq_left (by linarith)]; linarith
    have hB0 : f.eval B < 0 := hB B (by linarith)
    have hC0 : 0 < f.eval C := hA C hAC.le
    have hmem : (0:ℝ) ∈ Icc (f.eval B) (f.eval C) := by
      constructor <;> [exact le_of_lt hB0; exact le_of_lt hC0]
    have him := intermediate_value_Icc hBC.le hc.continuousOn hmem
    obtain ⟨c, _, hceq⟩ := him
    exact ⟨c, hceq⟩

/-- The real numbers form a real-closed field in the `IsRealClosed` hierarchy. -/
instance : IsRealClosed ℝ :=
  IsRealClosed.of_linearOrderedField
    (fun (hx : 0 ≤ (_ : ℝ)) => ⟨Real.sqrt _, by
      have h := Real.sq_sqrt hx
      rw [pow_two] at h
      exact h.symm⟩)
    (fun hf => exists_isRoot_of_odd_natDegree_real hf)

end RealClosed

end Hilbert17thProblem
