import Mathlib

namespace Hilbert17thProblem

open scoped BigOperators

noncomputable section

variable {R : Type*} [CommRing R]

/-- Membership normal form for the subsemiring generated by a preordering `P` and `a`. -/
theorem mem_closure_insert_preordering
    (P : RingPreordering R) (a : R) {x : R}
    (hx : x ∈ Subsemiring.closure (insert a (P : Set R))) :
    ∃ y z, (y : R) ∈ P ∧ z ∈ P ∧ x = y + a * z := by
  induction hx using Subsemiring.closure_induction with
  | mem x hx =>
      rcases hx with (rfl | hx)
      · exact ⟨0, 1, by simp, by simp, by simp⟩
      · exact ⟨x, 0, hx, by simp, by simp⟩
  | zero => exact ⟨0, 0, by simp, by simp, by simp⟩
  | one => exact ⟨1, 0, by simp, by simp, by simp⟩
  | add x y _ _ hx hy =>
      rcases hx with ⟨x₁, x₂, hx₁, hx₂, rfl⟩
      rcases hy with ⟨y₁, y₂, hy₁, hy₂, rfl⟩
      exact ⟨x₁ + y₁, x₂ + y₂, P.add_mem hx₁ hy₁, P.add_mem hx₂ hy₂, by ring⟩
  | mul x y _ _ hx hy =>
      rcases hx with ⟨x₁, x₂, hx₁, hx₂, rfl⟩
      rcases hy with ⟨y₁, y₂, hy₁, hy₂, rfl⟩
      exact ⟨x₁ * y₁ + (a * a) * (x₂ * y₂),
        x₁ * y₂ + y₁ * x₂,
        P.add_mem (P.mul_mem hx₁ hy₁)
        (P.mul_mem (P.mul_self_mem a) (P.mul_mem hx₂ hy₂)),
        P.add_mem (P.mul_mem hx₁ hy₂) (P.mul_mem hy₁ hx₂), by ring⟩


/-- The generated subsemiring is a preordering provided `-1` is absent. -/
def preorderingOfClosure
    (P : RingPreordering R) (a : R)
    (h : -1 ∉ Subsemiring.closure (insert a (P : Set R))) :
    RingPreordering R where
  toSubsemiring := Subsemiring.closure (insert a (P : Set R))
  mem_of_isSquare' {x hx} := by
    rcases hx with ⟨y, rfl⟩
    exact Subsemiring.subset_closure
      (Set.mem_insert_of_mem _ (P.mul_self_mem y))
  neg_one_notMem' := h

@[simp]
theorem mem_preorderingOfClosure {P : RingPreordering R} {a x : R}
    {h : -1 ∉ Subsemiring.closure (insert a (P : Set R))} :
    x ∈ preorderingOfClosure P a h ↔
      x ∈ Subsemiring.closure (insert a (P : Set R)) := Iff.rfl

theorem le_preorderingOfClosure (P : RingPreordering R) (a : R)
    (h : -1 ∉ Subsemiring.closure (insert a (P : Set R))) : P ≤ preorderingOfClosure P a h := by
  intro x hx
  exact Subsemiring.subset_closure (Set.mem_insert_of_mem _ hx)

theorem mem_preorderingOfClosure_insert (P : RingPreordering R) (a : R)
    (h : -1 ∉ Subsemiring.closure (insert a (P : Set R))) :
    a ∈ preorderingOfClosure P a h :=
  Subsemiring.subset_closure (Set.mem_insert _ _)

/-- If `- (x*y)` is nonnegative in a preordering, adjoining either factor cannot make `-1`
nonnegative in both generated preorderings. -/
theorem neg_one_notMem_closure_insert_or
    (P : RingPreordering R) {x y : R} (hxy : -(x * y) ∈ P) :
    -1 ∉ Subsemiring.closure (insert x (P : Set R)) ∨
      -1 ∉ Subsemiring.closure (insert y (P : Set R)) := by
  by_contra hcon
  have hx : -1 ∈ Subsemiring.closure (insert x (P : Set R)) := by
    by_contra hc
    exact hcon (Or.inl hc)
  have hy : -1 ∈ Subsemiring.closure (insert y (P : Set R)) := by
    by_contra hc
    exact hcon (Or.inr hc)
  clear hcon
  rcases mem_closure_insert_preordering P x hx with ⟨x₁, x₂, hx₁, hx₂, hex⟩
  rcases mem_closure_insert_preordering P y hy with ⟨y₁, y₂, hy₁, hy₂, hey⟩
  apply P.neg_one_notMem
  have key : -1 = -(x*y) * x₂ * y₂ + x₁ + y₁ + x₁ * y₁ := by
    linear_combination (y₁ + 1) * hex - 1 * x * x₂ * hey
  rw [key]
  have hprod : -(x*y) * x₂ * y₂ ∈ P :=
    P.mul_mem (P.mul_mem hxy hx₂) hy₂
  have hrest : x₁ + y₁ + x₁ * y₁ ∈ P :=
    P.add_mem (P.add_mem hx₁ hy₁) (P.mul_mem hx₁ hy₁)
  have : -(x*y) * x₂ * y₂ + (x₁ + y₁ + x₁ * y₁) ∈ P :=
    P.add_mem hprod hrest
  ring_nf at this ⊢
  exact this

/-- Construct a bundled preordering whose carrier is a specified subsemiring. -/
def preorderingOfSubsemiring
    (S : Subsemiring R)
    (hsq : ∀ x, IsSquare x → x ∈ S)
    (hne : -1 ∉ S) : RingPreordering R where
  toSubsemiring := S
  mem_of_isSquare' := fun hx => hsq _ hx
  neg_one_notMem' := hne

@[simp]
theorem mem_preorderingOfSubsemiring
    {S : Subsemiring R} {hsq hne x} :
    x ∈ preorderingOfSubsemiring S hsq hne ↔ x ∈ S := Iff.rfl

theorem sSup_preordering
    {C : Set (RingPreordering R)} (hne : C.Nonempty)
    (hdir : DirectedOn (· ≤ ·) C) :
    ∃ Q : RingPreordering R, ∀ P ∈ C, P ≤ Q := by
  have hmem : ∀ x ∈ sSup ((fun P => P.toSubsemiring) '' C),
      ∃ P ∈ C, x ∈ P := by
    intro x hx
    have himage : ((fun P => P.toSubsemiring) '' C).Nonempty :=
      Set.Nonempty.image (fun P => P.toSubsemiring) hne
    have hdirS : DirectedOn (· ≤ ·) ((fun P => P.toSubsemiring) '' C) := by
      rintro S₁ ⟨P₁, hP₁, rfl⟩ S₂ ⟨P₂, hP₂, rfl⟩
      rcases hdir P₁ hP₁ P₂ hP₂ with ⟨Q, hQ₁, hQ₂, hQ₃⟩
      exact ⟨Q.toSubsemiring, ⟨Q, hQ₁, rfl⟩, hQ₂, hQ₃⟩
    simpa using (Subsemiring.mem_sSup_of_directedOn himage hdirS).mp hx
  refine ⟨preorderingOfSubsemiring (sSup ((fun P => P.toSubsemiring) '' C))
    (fun x hx => ?_) (fun h => ?_), fun P hP x hx => ?_⟩
  · rcases hne with ⟨Z, hZ⟩
    have hxs : x ∈ Z := Z.mem_of_isSquare hx
    have hxsup : x ∈ sSup ((fun P => P.toSubsemiring) '' C) :=
      (le_sSup (Set.mem_image_of_mem (fun P => P.toSubsemiring) hZ)) hxs
    exact hxsup
  · rcases hne with ⟨Q, hQ⟩
    rcases hmem (-1) h with ⟨Z, hZ, hmem1⟩
    exact Z.neg_one_notMem hmem1
  · have hxsup : x ∈ sSup ((fun Q => Q.toSubsemiring) '' C) :=
      (le_sSup (Set.mem_image_of_mem (fun Q => Q.toSubsemiring) hP)) hx
    exact hxsup

/-- Every preordering is bounded by a maximal preordering above it. -/
theorem exists_maximal_preordering
    (P : RingPreordering R) :
    ∃ Q : RingPreordering R, P ≤ Q ∧ Maximal (fun Q => P ≤ Q) Q := by
  have hzorn := zorn_le_nonempty₀ {Q : RingPreordering R | P ≤ Q}
    (fun C hC hchain y hy => by
      have hne : C.Nonempty := ⟨y, hy⟩
      have hdir : DirectedOn (· ≤ ·) C := hchain.directedOn
      rcases sSup_preordering hne hdir with ⟨Q, hQ⟩
      exact ⟨Q, le_trans (hC hy) (hQ y hy), fun z hz => hQ z hz⟩)
    P (Set.mem_setOf_eq.mpr le_rfl)
  exact ⟨hzorn.choose, hzorn.choose_spec.1, hzorn.choose_spec.2⟩

end

end Hilbert17thProblem
