/-
Copyright (c) 2026 Mocho Go. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Mocho Go
-/

import Mathlib.Algebra.Order.Ring.Ordering.Basic
import Mathlib.Algebra.Order.Algebra
import Mathlib.Order.Zorn
import Hilbert17thProblem.RW.Ordering.Basic

/-!
# Extending a ring preordering to an ordering

The construction below is the field case of the usual maximal-preordering
argument.  The preordering generated by `x` has the particularly simple form
`p + x * q`, since every square already belongs to the original cone.
-/

namespace RingPreordering

section

variable {K : Type*} [Field K]

private def adjoinSet (P : RingPreordering K) (x : K) : Set K :=
  {z | ∃ p q : K, p ∈ P ∧ q ∈ P ∧ z = p + x * q}

private theorem adjoinSet_add
    (P : RingPreordering K) (x : K) {u v : K}
    (hu : u ∈ adjoinSet P x) (hv : v ∈ adjoinSet P x) :
    u + v ∈ adjoinSet P x := by
  rcases hu with ⟨p, q, hp, hq, rfl⟩
  rcases hv with ⟨r, s, hr, hs, rfl⟩
  refine ⟨p + r, q + s, add_mem hp hr, add_mem hq hs, ?_⟩
  ring

private theorem adjoinSet_mul
    (P : RingPreordering K) (x : K) {u v : K}
    (hu : u ∈ adjoinSet P x) (hv : v ∈ adjoinSet P x) :
    u * v ∈ adjoinSet P x := by
  rcases hu with ⟨p, q, hp, hq, rfl⟩
  rcases hv with ⟨r, s, hr, hs, rfl⟩
  refine ⟨p * r + x ^ 2 * (q * s), p * s + q * r,
    add_mem (mul_mem hp hr) (mul_mem (P.pow_two_mem x) (mul_mem hq hs)),
    add_mem (mul_mem hp hs) (mul_mem hq hr), ?_⟩
  ring

private theorem adjoinSet_sq
    (P : RingPreordering K) (x y : K) :
    y * y ∈ adjoinSet P x := by
  refine ⟨y * y, 0, P.mul_self_mem y, zero_mem P, ?_⟩
  ring

private def adjoin
    (P : RingPreordering K) (x : K)
    (h : -1 ∉ adjoinSet P x) : RingPreordering K :=
  RingPreordering.mk' (adjoinSet P x)
    (adjoinSet_add P x) (adjoinSet_mul P x) (adjoinSet_sq P x) h

private theorem le_adjoin
    (P : RingPreordering K) (x : K)
    (h : -1 ∉ adjoinSet P x) :
    P ≤ adjoin P x h := by
  intro z hz
  exact ⟨z, 0, hz, zero_mem P, by simp⟩

private theorem mem_adjoin
    (P : RingPreordering K) (x : K)
    (h : -1 ∉ adjoinSet P x) :
    x ∈ adjoin P x h := by
  exact ⟨0, 1, zero_mem P, one_mem P, by simp⟩

private def chainSup
    (c : Set (RingPreordering K))
    (hc : IsChain (fun P Q : RingPreordering K => P ≤ Q) c)
    (hne : c.Nonempty) : RingPreordering K :=
  RingPreordering.mk' (⋃ P ∈ c, (P : Set K))
    (by
      intro u v hu hv
      rcases Set.mem_iUnion₂.mp hu with ⟨P, hPc, huP⟩
      rcases Set.mem_iUnion₂.mp hv with ⟨Q, hQc, hvQ⟩
      by_cases hPQ : P = Q
      · subst Q
        exact Set.mem_iUnion₂.mpr ⟨P, hPc, add_mem huP hvQ⟩
      rcases hc hPc hQc hPQ with hPQ' | hQP
      · exact Set.mem_iUnion₂.mpr ⟨Q, hQc, add_mem (hPQ' huP) hvQ⟩
      · exact Set.mem_iUnion₂.mpr ⟨P, hPc, add_mem huP (hQP hvQ)⟩)
    (by
      intro u v hu hv
      rcases Set.mem_iUnion₂.mp hu with ⟨P, hPc, huP⟩
      rcases Set.mem_iUnion₂.mp hv with ⟨Q, hQc, hvQ⟩
      by_cases hPQ : P = Q
      · subst Q
        exact Set.mem_iUnion₂.mpr ⟨P, hPc, mul_mem huP hvQ⟩
      rcases hc hPc hQc hPQ with hPQ' | hQP
      · exact Set.mem_iUnion₂.mpr ⟨Q, hQc, mul_mem (hPQ' huP) hvQ⟩
      · exact Set.mem_iUnion₂.mpr ⟨P, hPc, mul_mem huP (hQP hvQ)⟩)
    (by
      intro x
      rcases hne with ⟨P, hPc⟩
      exact Set.mem_iUnion₂.mpr ⟨P, hPc, P.mul_self_mem x⟩)
    (by
      intro h
      rcases Set.mem_iUnion₂.mp h with ⟨P, hPc, hP⟩
      exact P.neg_one_notMem hP)

private theorem le_chainSup
    (c : Set (RingPreordering K))
    (hc : IsChain (fun P Q : RingPreordering K => P ≤ Q) c)
    (hne : c.Nonempty) {P : RingPreordering K} (hPc : P ∈ c) :
    P ≤ chainSup c hc hne := by
  intro x hx
  exact Set.mem_iUnion₂.mpr ⟨P, hPc, hx⟩

private theorem exists_maximal_containing
    (P : RingPreordering K) :
    ∃ M : RingPreordering K, P ≤ M ∧
      ∀ Q : RingPreordering K, M ≤ Q → Q ≤ M := by
  let S : Type _ := {Q : RingPreordering K // P ≤ Q}
  have hchains :
      ∀ c : Set S, IsChain (fun Q R : S => Q ≤ R) c → BddAbove c := by
    intro c hc
    by_cases hne : c.Nonempty
    · let c' : Set (RingPreordering K) :=
        Set.range (fun Q : c => (Q : RingPreordering K))
      have hc' : IsChain (fun Q R : RingPreordering K => Q ≤ R) c' := by
        rintro Q ⟨q, rfl⟩ R ⟨r, rfl⟩ hQR
        have hqr : (q : S) ≠ (r : S) := by
          intro h
          apply hQR
          exact congrArg (fun z : S => (z : RingPreordering K)) h
        rcases hc q.property r.property hqr with hqr' | hrq
        · exact Or.inl hqr'
        · exact Or.inr hrq
      have hne' : c'.Nonempty := by
        rcases hne with ⟨q, hq⟩
        exact ⟨(q : RingPreordering K), ⟨⟨q, hq⟩, rfl⟩⟩
      let U : RingPreordering K := chainSup c' hc' hne'
      have hPU : P ≤ U := by
        rcases hne with ⟨q, hq⟩
        exact le_trans q.property
          (le_chainSup c' hc' hne'
            (show (q : RingPreordering K) ∈ c' from ⟨⟨q, hq⟩, rfl⟩))
      refine ⟨⟨U, hPU⟩, ?_⟩
      intro q hq
      exact le_chainSup c' hc' hne'
        (show (q : RingPreordering K) ∈ c' from ⟨⟨q, hq⟩, rfl⟩)
    · refine ⟨⟨P, le_rfl⟩, ?_⟩
      intro q hq
      exact False.elim (hne ⟨q, hq⟩)
  rcases zorn_le hchains with ⟨M, hM⟩
  refine ⟨M, M.property, ?_⟩
  intro Q hMQ
  have hPQ : P ≤ Q := le_trans M.property hMQ
  have hMsub : M ≤ (⟨Q, hPQ⟩ : S) := hMQ
  exact hM hMsub

/-- Every preordering on a field is contained in an ordering. -/
theorem exists_le_isOrdering (P : RingPreordering K) :
    ∃ O : RingPreordering K, P ≤ O ∧ O.IsOrdering := by
  rcases exists_maximal_containing P with ⟨O, hPO, hOmax⟩
  have hmem : ∀ x : K, x ∈ O ∨ -x ∈ O := by
    intro x
    by_contra h
    push Not at h
    rcases h with ⟨hx, hnx⟩
    have hbad : ∀ y : K, y ∉ O → -1 ∈ adjoinSet O y := by
      intro y hy
      by_contra hproper
      let Q := adjoin O y hproper
      have hOQ : O ≤ Q := le_adjoin O y hproper
      have hQO : Q ≤ O := hOmax Q hOQ
      exact hy (hQO (mem_adjoin O y hproper))
    rcases hbad x hx with ⟨p, q, hp, hq, hxpq⟩
    rcases hbad (-x) hnx with ⟨r, s, hr, hs, hxr⟩
    have hcancel : -(q + s) = p * s + r * q := by
      have h1 : (-1 : K) * s = (p + x * q) * s := congrArg (fun z => z * s) hxpq
      have h2 : (-1 : K) * q = (r + (-x) * s) * q := congrArg (fun z => z * q) hxr
      calc
        -(q + s) = (-1) * s + (-1) * q := by ring
        _ = (p + x * q) * s + (-1) * q := by rw [h1]
        _ = (p + x * q) * s + (r + (-x) * s) * q := by rw [h2]
        _ = p * s + r * q := by ring
    have hneg_sum : -(q + s) ∈ O := by
      rw [hcancel]
      exact add_mem (mul_mem hp hs) (mul_mem hr hq)
    have hsum : q + s ∈ O := add_mem hq hs
    have hsum_zero : q + s = 0 := O.eq_zero_of_mem_of_neg_mem hsum hneg_sum
    have hq_neg : -q ∈ O := by
      rw [neg_eq_of_add_eq_zero_right hsum_zero]
      exact hs
    have hq_zero : q = 0 := O.eq_zero_of_mem_of_neg_mem hq hq_neg
    have hneg_one : -1 ∈ O := by
      rw [hxpq, hq_zero]
      simpa using hp
    exact O.neg_one_notMem hneg_one
  refine ⟨O, hPO, ?_⟩
  rw [isOrdering_iff]
  intro a b hneg
  rcases hmem a with ha | hna
  · exact Or.inl ha
  rcases hmem b with hb | hnb
  · exact Or.inr hb
  have hab : a * b ∈ O := by
    simpa [neg_mul_neg] using mul_mem hna hnb
  have hab_zero : a * b = 0 := O.eq_zero_of_mem_of_neg_mem hab hneg
  rcases mul_eq_zero.mp hab_zero with ha0 | hb0
  · exact Or.inl (by simp [ha0])
  · exact Or.inr (by simp [hb0])

end
section BaseSquare
variable {F K : Type*} [Field F] [Field K] [Algebra F K]
  [LinearOrder F] [hF : IsStrictOrderedRing F]
/-- Generators for the cone obtained by adjoining the base nonnegative cone and all
squares in an `F`-algebra field `K`. -/
def baseSquareGenerators : Set K :=
  {z | ∃ a : F, 0 ≤ a ∧ z = algebraMap F K a} ∪
    {z | ∃ y : K, z = y * y}

/-- The explicit subsemiring generated by the base nonnegative cone and all squares. -/
def baseSquareSubsemiring : Subsemiring K :=
  Subsemiring.closure (baseSquareGenerators (F := F) (K := K))

/-- Bundle `baseSquareSubsemiring` as a ring preordering once properness is supplied. -/
def baseSquarePreordering
    (hproper : (-1 : K) ∉ baseSquareSubsemiring (F := F) (K := K)) :
    RingPreordering K :=
  RingPreordering.mk' (baseSquareSubsemiring (F := F) (K := K) : Set K)
    (by
      intro x y hx hy
      exact add_mem hx hy)
    (by
      intro x y hx hy
      exact mul_mem hx hy)
    (by
      intro x
      exact Subsemiring.subset_closure (show x * x ∈
        baseSquareGenerators (F := F) (K := K) from
          Or.inr ⟨x, rfl⟩))
    hproper

omit [IsStrictOrderedRing F] in
theorem mem_baseSquarePreordering_algebraMap
    (hproper : (-1 : K) ∉ baseSquareSubsemiring (F := F) (K := K))
    {a : F} (ha : 0 ≤ a) :
    algebraMap F K a ∈ baseSquarePreordering (F := F) (K := K) hproper := by
  exact Subsemiring.subset_closure (show algebraMap F K a ∈
    baseSquareGenerators (F := F) (K := K) from
      Or.inl ⟨a, ha, rfl⟩)

omit [IsStrictOrderedRing F] in
private def baseSquareWeightedTerm (a : F) (x : K) : K :=
  algebraMap F K a * (x * x)

private def baseSquareWeightedTerms : Set K :=
  {z | ∃ a : F, ∃ x : K, 0 ≤ a ∧ z = baseSquareWeightedTerm (F := F) (K := K) a x}

private def baseSquareWeightedCone : AddSubmonoid K :=
  AddSubmonoid.closure (baseSquareWeightedTerms (F := F) (K := K))

private theorem baseSquareWeightedTerms_mul
    {a b : F} {x y : K} (ha : 0 ≤ a) (hb : 0 ≤ b) :
    baseSquareWeightedTerm (F := F) (K := K) a x *
        baseSquareWeightedTerm (F := F) (K := K) b y ∈
      baseSquareWeightedTerms (F := F) (K := K) := by
  refine ⟨a * b, x * y, mul_nonneg ha hb, ?_⟩
  simp [baseSquareWeightedTerm, ← map_mul, mul_assoc, mul_left_comm, mul_comm]

private theorem baseSquareWeightedCone_mul_mem
    {x y : K} (hx : x ∈ baseSquareWeightedCone (F := F) (K := K))
    (hy : y ∈ baseSquareWeightedCone (F := F) (K := K)) :
    x * y ∈ baseSquareWeightedCone (F := F) (K := K) := by
  have hterm_mul : ∀ {z : K}, z ∈ baseSquareWeightedTerms (F := F) (K := K) →
      ∀ {w : K}, w ∈ baseSquareWeightedCone (F := F) (K := K) →
        z * w ∈ baseSquareWeightedCone (F := F) (K := K) := by
    intro z hz w hw
    induction hw using AddSubmonoid.closure_induction with
    | zero => simp
    | add w₁ w₂ _ _ hw₁ hw₂ =>
        rw [mul_add]
        exact add_mem hw₁ hw₂
    | mem w hw =>
        rcases hz with ⟨a, u, ha, rfl⟩
        rcases hw with ⟨b, v, hb, rfl⟩
        exact AddSubmonoid.subset_closure (baseSquareWeightedTerms_mul ha hb)
  have hcone_mul : ∀ {z : K}, z ∈ baseSquareWeightedCone (F := F) (K := K) →
      z * y ∈ baseSquareWeightedCone (F := F) (K := K) := by
    intro z hz
    induction hz using AddSubmonoid.closure_induction with
    | zero => simp
    | add z₁ z₂ _ _ hz₁ hz₂ =>
        rw [add_mul]
        exact add_mem hz₁ hz₂
    | mem z hz => exact hterm_mul hz hy
  exact hcone_mul hx

omit [IsStrictOrderedRing F] in
private theorem baseSquareWeightedCone_base
    {a : F} (ha : 0 ≤ a) :
    algebraMap F K a ∈ baseSquareWeightedCone (F := F) (K := K) := by
  refine AddSubmonoid.subset_closure ⟨a, 1, ha, ?_⟩
  simp [baseSquareWeightedTerm]

private theorem baseSquareWeightedCone_square (x : K) :
    x * x ∈ baseSquareWeightedCone (F := F) (K := K) := by
  refine AddSubmonoid.subset_closure ⟨1, x, zero_le_one, ?_⟩
  simp [baseSquareWeightedTerm]

private theorem baseSquareWeightedCone_one :
    (1 : K) ∈ baseSquareWeightedCone (F := F) (K := K) := by
  refine AddSubmonoid.subset_closure ⟨1, 1, zero_le_one, ?_⟩
  simp [baseSquareWeightedTerm]

private def baseSquareWeightedSubsemiring : Subsemiring K where
  carrier := baseSquareWeightedCone (F := F) (K := K)
  zero_mem' := (baseSquareWeightedCone (F := F) (K := K)).zero_mem
  one_mem' := baseSquareWeightedCone_one (F := F) (K := K)
  add_mem' := (baseSquareWeightedCone (F := F) (K := K)).add_mem
  mul_mem' := baseSquareWeightedCone_mul_mem

private theorem baseSquareSubsemiring_le_baseSquareWeightedSubsemiring :
    baseSquareSubsemiring (F := F) (K := K) ≤
      baseSquareWeightedSubsemiring (F := F) (K := K) := by
  apply Subsemiring.closure_le.2
  intro z hz
  rcases hz with ⟨a, ha, rfl⟩ | ⟨x, rfl⟩
  · exact baseSquareWeightedCone_base ha
  · exact baseSquareWeightedCone_square x

private theorem baseSquareWeightedCone_nonneg_of_projection
    (π : K →ₗ[F] F) (hπ : ∀ x : K, x ≠ 0 → 0 < π (x * x))
    {x : K} (hx : x ∈ baseSquareWeightedCone (F := F) (K := K)) :
    0 ≤ π x := by
  induction hx using AddSubmonoid.closure_induction with
  | zero => simp
  | add x y _ _ hx hy =>
      rw [map_add]
      exact add_nonneg hx hy
  | mem z hz =>
      rcases hz with ⟨a, y, ha, rfl⟩
      by_cases hy : y = 0
      · subst y
        simp [baseSquareWeightedTerm]
      have hysq : 0 < π (y * y) := hπ y hy
      have hscale : 0 ≤ a * π (y * y) := mul_nonneg ha hysq.le
      rw [baseSquareWeightedTerm, ← Algebra.smul_def, map_smul]
      simpa [smul_eq_mul] using hscale

/-- A strictly positive square projection makes the base-square cone proper. -/
theorem baseSquareSubsemiring_proper_of_projection
    (π : K →ₗ[F] F) (hπ : ∀ x : K, x ≠ 0 → 0 < π (x * x)) :
    (-1 : K) ∉ baseSquareSubsemiring (F := F) (K := K) := by
  intro hneg
  have hcone : (-1 : K) ∈ baseSquareWeightedCone (F := F) (K := K) :=
    baseSquareSubsemiring_le_baseSquareWeightedSubsemiring hneg
  have hnonneg : 0 ≤ π (-1 : K) :=
    baseSquareWeightedCone_nonneg_of_projection π hπ hcone
  have hpos : 0 < π (1 : K) := by
    simpa using hπ (1 : K) one_ne_zero
  have hneg_eval : π (-1 : K) < 0 := by
    simpa using (neg_lt_zero.mpr hpos)
  exact (not_lt_of_ge hnonneg) hneg_eval

/-- A proper base/squares cone extends to an ordered field structure on `K`.

The order returned here is the canonical order induced by the resulting ordering
preordering.  In particular the statement is independent of any ambient order on
`K`; callers can install `linearOrderOfIsOrdering` and
`isStrictOrderedRingOfIsOrdering` as local instances using the returned `O.IsOrdering`. -/
theorem exists_orderedAlgebraExtension_of_baseSquareSubsemiring
    (hproper : (-1 : K) ∉ baseSquareSubsemiring (F := F) (K := K)) :
    ∃ (O : RingPreordering K) (hO : O.IsOrdering),
      (∀ a : F, 0 ≤ a →
        @LE.le K
          (@RatFuncWittLocalGlobal.RingPreordering.linearOrderOfIsOrdering K _ O hO).toLE
          0 (algebraMap F K a)) ∧
      (∀ a : F, 0 < a →
        @LT.lt K
          (@RatFuncWittLocalGlobal.RingPreordering.linearOrderOfIsOrdering K _ O hO).toLT
          0 (algebraMap F K a)) := by
  let P : RingPreordering K :=
    baseSquarePreordering (F := F) (K := K) hproper
  rcases exists_le_isOrdering P with ⟨O, hPO, hO⟩
  refine ⟨O, hO, ?_, ?_⟩
  · intro a ha
    apply (@RatFuncWittLocalGlobal.RingPreordering.zero_le_linearOrderOfIsOrdering_iff K _ O hO).mpr
    have hmem : algebraMap F K a ∈ O :=
      hPO (mem_baseSquarePreordering_algebraMap
        (F := F) (K := K) hproper ha)
    have hone : (1 : K) ∈ O := by
      have hbase : (0 : F) ≤ 1 := zero_le_one
      rw [← (algebraMap F K).map_one]
      exact hPO (mem_baseSquarePreordering_algebraMap
        (F := F) (K := K) hproper hbase)
    have hmul : algebraMap F K a * (1 : K) ∈ O := mul_mem hmem hone
    simpa using hmul
  · intro a ha
    have hmem : algebraMap F K a ∈ O :=
      hPO (mem_baseSquarePreordering_algebraMap
        (F := F) (K := K) hproper ha.le)
    have hneg : -algebraMap F K a ∉ O := by
      intro hneg
      have hz : algebraMap F K a = 0 :=
        O.eq_zero_of_mem_of_neg_mem hmem hneg
      have hane : algebraMap F K a ≠ 0 := by
        intro hzero
        have hzero' : algebraMap F K (a * a⁻¹) = 0 := by
          simp [hzero]
        have hmul : a * a⁻¹ = (1 : F) := mul_inv_cancel₀ ha.ne'
        rw [hmul, map_one] at hzero'
        exact one_ne_zero hzero'
      exact hane hz
    exact (@RatFuncWittLocalGlobal.RingPreordering.strictPos_iff_zero_lt_linearOrderOfIsOrdering
      K _ O hO).mp
      ⟨hmem, hneg⟩

/-- A strictly positive square projection supplies an ordered algebra extension. -/
theorem exists_orderedAlgebraExtension_of_projection
    (π : K →ₗ[F] F) (hπ : ∀ x : K, x ≠ 0 → 0 < π (x * x)) :
    ∃ (O : RingPreordering K) (hO : O.IsOrdering),
      (∀ a : F, 0 ≤ a →
        @LE.le K
          (@RatFuncWittLocalGlobal.RingPreordering.linearOrderOfIsOrdering K _ O hO).toLE
          0 (algebraMap F K a)) ∧
      (∀ a : F, 0 < a →
        @LT.lt K
          (@RatFuncWittLocalGlobal.RingPreordering.linearOrderOfIsOrdering K _ O hO).toLT
          0 (algebraMap F K a)) := by
  apply exists_orderedAlgebraExtension_of_baseSquareSubsemiring
  exact baseSquareSubsemiring_proper_of_projection π hπ

/-- The same projection witness also makes the scalar map monotone for the induced order. -/
theorem exists_orderedAlgebraExtension_with_algebraMap_monotone_of_projection
    (π : K →ₗ[F] F) (hπ : ∀ x : K, x ≠ 0 → 0 < π (x * x)) :
    ∃ (O : RingPreordering K) (hO : O.IsOrdering),
      (∀ a : F, 0 ≤ a →
        @LE.le K
          (@RatFuncWittLocalGlobal.RingPreordering.linearOrderOfIsOrdering K _ O hO).toLE
          0 (algebraMap F K a)) ∧
      (∀ a : F, 0 < a →
        @LT.lt K
          (@RatFuncWittLocalGlobal.RingPreordering.linearOrderOfIsOrdering K _ O hO).toLT
          0 (algebraMap F K a)) ∧
      (∀ ⦃a b : F⦄, a ≤ b →
        @LE.le K
          (@RatFuncWittLocalGlobal.RingPreordering.linearOrderOfIsOrdering K _ O hO).toLE
          (algebraMap F K a) (algebraMap F K b)) := by
  rcases exists_orderedAlgebraExtension_of_projection π hπ with ⟨O, hO, hnonneg, hpos⟩
  refine ⟨O, hO, hnonneg, hpos, ?_⟩
  intro a b hab
  apply (@RatFuncWittLocalGlobal.RingPreordering.le_linearOrderOfIsOrdering_iff K _ O hO).mpr
  have hdiff :
      @LE.le K
        (@RatFuncWittLocalGlobal.RingPreordering.linearOrderOfIsOrdering K _ O hO).toLE
        0 (algebraMap F K (b - a)) :=
    hnonneg (b - a) (sub_nonneg.mpr hab)
  have hmem : algebraMap F K (b - a) ∈ O :=
    (@RatFuncWittLocalGlobal.RingPreordering.zero_le_linearOrderOfIsOrdering_iff K _ O hO).mp hdiff
  simpa using hmem

end BaseSquare

end RingPreordering
