/-
Copyright (c) 2026 Mocho Go. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Mocho Go
-/

import Hilbert17thProblem.RW.RealClosure.Odd.Order
import Hilbert17thProblem.RW.RealClosure.Odd.Lift
import Hilbert17thProblem.RW.RealClosure.Odd.Basic

/-!
# Strong-induction data for the odd bounded cone

This file starts the properness argument by extracting a strictly smaller odd
irreducible factor from a hypothetical divisibility `f ∣ g + 1`.  The actual
evaluation/lift step is kept separate from this polynomial degree package.
-/

namespace RatFuncWittLocalGlobal

open scoped _root_.Polynomial
open _root_.Polynomial

universe u

namespace OrderedRealClosure

variable {F : Type u} [Field F] [LinearOrder F] [IsStrictOrderedRing F]

/--
If an odd monic irreducible polynomial divides `g + 1` for a bounded-cone
element `g`, then the quotient has odd degree and contains a strictly smaller
odd monic irreducible factor.
-/
theorem odd_quotient_data_of_dvd_add_one
    {f g : Polynomial F}
    (hfM : f.Monic) (hfI : Irreducible f) (hfO : Odd f.natDegree)
    (hg : g ∈ boundedSquarePolynomialCone (F := F) f.natDegree)
    (hdiv : f ∣ g + 1) :
    ∃ k k' : Polynomial F,
      g + 1 = f * k ∧ k ≠ 0 ∧ Odd k'.natDegree ∧ k'.Monic ∧
        Irreducible k' ∧ k' ∣ k ∧ k'.natDegree < f.natDegree := by
  obtain ⟨k, hk⟩ := dvd_iff_exists_eq_mul_right.mp hdiv
  have hfg0 : f ≠ 0 := hfM.ne_zero
  have hgnonneg : 0 ≤ g.leadingCoeff :=
    (oddPolynomialCone.invariant hfI.natDegree_pos hg).1
  have hgp0 : g + 1 ≠ 0 := by
    intro hzero
    have hgneg : g = -1 := eq_neg_of_add_eq_zero_left hzero
    have hlcneg : g.leadingCoeff = -1 := by
      rw [hgneg, Polynomial.leadingCoeff_neg, Polynomial.leadingCoeff_one]
    rw [hlcneg] at hgnonneg
    exact (not_le_of_gt neg_one_lt_zero) hgnonneg
  have hk0 : k ≠ 0 := by
    intro hkzero
    apply hgp0
    rw [hk, hkzero, mul_zero]
  have hdegree : g.natDegree = f.natDegree + k.natDegree := by
    calc
      g.natDegree = (g + 1).natDegree := by
        symm
        simpa only [Polynomial.C_1] using
          (Polynomial.natDegree_add_C (p := g) (a := (1 : F)))
      _ = (f * k).natDegree := by rw [hk]
      _ = f.natDegree + k.natDegree := Polynomial.natDegree_mul hfg0 hk0
  have hgbound : g.natDegree < 2 * f.natDegree :=
    (oddPolynomialCone.invariant hfI.natDegree_pos hg).2.2
  have hklt : k.natDegree < f.natDegree := by
    omega
  have hkodd : Odd k.natDegree := by
    apply (Nat.not_even_iff_odd).mp
    intro hkeven
    have hsumodd : Odd (f.natDegree + k.natDegree) := hfO.add_even hkeven
    have hgodd : Odd g.natDegree := by simpa [hdegree] using hsumodd
    exact (Nat.not_odd_iff_even.mpr
      (oddPolynomialCone.invariant hfI.natDegree_pos hg).2.1) hgodd
  obtain ⟨k', hk'odd, hk'monic, hk'irr, hk'dvd⟩ :=
    RatFuncWittLocalGlobal.Polynomial.exists_odd_natDegree_monic_irreducible_factor hkodd
  have hk'lt : k'.natDegree < f.natDegree := by
    exact lt_of_le_of_lt (Polynomial.natDegree_le_of_dvd hk'dvd hk0) hklt
  exact ⟨k, k', hk, hk0, hk'odd, hk'monic, hk'irr, hk'dvd, hk'lt⟩

/--
The bounded square cone contains no `g` for which an odd monic irreducible
polynomial divides `g + 1`.  The recursive step is performed in the simple
field generated by an odd irreducible factor of the quotient.
-/
theorem not_dvd_add_one_of_mem_boundedSquarePolynomialCone
    {f g : Polynomial F}
    (hfM : f.Monic) (hfI : Irreducible f) (hfO : Odd f.natDegree)
    (hg : g ∈ boundedSquarePolynomialCone (F := F) f.natDegree) :
    ¬ f ∣ g + 1 := by
  have hmain : ∀ n : ℕ, ∀ f g : Polynomial F,
      f.natDegree = n → f.Monic → Irreducible f → Odd f.natDegree →
      g ∈ boundedSquarePolynomialCone (F := F) n → ¬ f ∣ g + 1 := by
    intro n
    induction n using Nat.strong_induction_on with
    | h n ih =>
      intro f g hfn hfm hfi hfo hgm hdiv
      obtain ⟨k, k', hk, hk0, hk'odd, hk'monic, hk'irr, hk'dvd, hk'lt⟩ :=
        odd_quotient_data_of_dvd_add_one hfm hfi hfo (by simpa [hfn] using hgm) hdiv
      let _ : Fact (Irreducible k') := ⟨hk'irr⟩
      have hk_eval : Polynomial.aeval (AdjoinRoot.root k') k = 0 := by
        rw [AdjoinRoot.aeval_eq]
        exact (AdjoinRoot.mk_eq_zero).2 hk'dvd
      have hgaeval : Polynomial.aeval (AdjoinRoot.root k') (g + 1) = 0 := by
        rw [hk, Polynomial.aeval_mul, hk_eval, mul_zero]
      have hgeval : Polynomial.aeval (AdjoinRoot.root k') g = -1 := by
        apply eq_neg_of_add_eq_zero_left
        simpa [Polynomial.aeval_add] using hgaeval
      have hgspan :
          Polynomial.aeval (AdjoinRoot.root k') g ∈
            baseSquareSpan (F := F) (K := AdjoinRoot k') :=
        boundedSquarePolynomialCone_aeval_mem_baseSquareSpan
          (F := F) (K := AdjoinRoot k') (by simpa [hfn] using hgm)
          (AdjoinRoot.root k')
      have hminusspan : (-1 : AdjoinRoot k') ∈
          baseSquareSpan (F := F) (K := AdjoinRoot k') := by
        rw [← hgeval]
        exact hgspan
      let pb : PowerBasis F (AdjoinRoot k') := AdjoinRoot.powerBasis' hk'monic
      obtain ⟨g', hg'eval, hg'cone⟩ :=
        mem_baseSquareSpan_aeval (F := F) (K := AdjoinRoot k') pb hminusspan
      have hpb_dim : pb.dim = k'.natDegree := by
        change (AdjoinRoot.powerBasis' hk'monic).dim = k'.natDegree
        rfl
      rw [hpb_dim] at hg'cone
      have hg'eval' : Polynomial.aeval (AdjoinRoot.root k') g' = -1 := by
        simpa [pb, AdjoinRoot.powerBasis'_gen hk'monic] using hg'eval
      have hrootg' : Polynomial.aeval (AdjoinRoot.root k') (g' + 1) = 0 := by
        rw [Polynomial.aeval_add, hg'eval', Polynomial.aeval_one]
        simp
      have hmk : (AdjoinRoot.mk k') (g' + 1) = 0 := by
        rw [← AdjoinRoot.aeval_eq]
        exact hrootg'
      have hk'dvdg' : k' ∣ g' + 1 := (AdjoinRoot.mk_eq_zero).mp hmk
      have hk'lt_n : k'.natDegree < n := by simpa [hfn] using hk'lt
      exact ih k'.natDegree hk'lt_n k' g' rfl hk'monic hk'irr hk'odd hg'cone hk'dvdg'
  exact hmain f.natDegree f g rfl hfM hfI hfO hg

end OrderedRealClosure
end RatFuncWittLocalGlobal
