/-
Copyright (c) 2026 Mocho Go. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Mocho Go
-/

import Hilbert17thProblem.RW.RealClosure.Odd.Order

/-!
# Bounded square-cone lifts along a power basis

This file records the finite-degree bridge between the cone generated by
squares in a field extension and the bounded polynomial square cone.  The
bridge is deliberately stated for an arbitrary field power basis, so that it
can be reused by the simple-adjunction and adjoin-root arguments.
-/

namespace RatFuncWittLocalGlobal

open scoped _root_.Polynomial
open _root_.Polynomial

universe u v

namespace OrderedRealClosure

variable {F : Type u} [Field F] [LinearOrder F] [IsStrictOrderedRing F]
  {K : Type v} [Field K] [Algebra F K]

/-- The additive cone in `K` generated by nonnegative base scalars and squares. -/
noncomputable def baseSquareSpan : Submodule (Subsemiring.nonneg F) K :=
  Submodule.span (Subsemiring.nonneg F) {x : K | IsSquare x}

/-- A bounded polynomial square cone element evaluates to an element of the
base-square span, for every evaluation point in the extension field. -/
theorem boundedSquarePolynomialCone_aeval_mem_baseSquareSpan
    {n : ℕ} {g : Polynomial F}
    (hg : g ∈ boundedSquarePolynomialCone (F := F) n) (x : K) :
    Polynomial.aeval x g ∈ baseSquareSpan (F := F) (K := K) := by
  refine Submodule.span_induction (p := fun p _ =>
    Polynomial.aeval x p ∈ baseSquareSpan (F := F) (K := K)) ?_ ?_ ?_ ?_ hg
  · intro p hp
    rcases hp with ⟨r, _, rfl⟩
    apply Submodule.subset_span
    change IsSquare (Polynomial.aeval x (r * r))
    rw [Polynomial.aeval_mul]
    exact ⟨Polynomial.aeval x r, rfl⟩
  · simp
  · intro p q hp hq ihp ihq
    rw [Polynomial.aeval_add]
    exact (baseSquareSpan (F := F) (K := K)).add_mem ihp ihq
  · intro a p hp ihp
    have h_eval : Polynomial.aeval x (a • p) =
        a • Polynomial.aeval x p := by
      change Polynomial.aeval x ((a : F) • p) =
        (a : F) • Polynomial.aeval x p
      rw [map_smul]
    rw [h_eval]
    exact (baseSquareSpan (F := F) (K := K)).smul_mem a ihp

/-- Every element of the base-square span has a bounded polynomial lift along
a power basis. -/
theorem mem_baseSquareSpan_aeval
    (pb : PowerBasis F K) {x : K}
    (hx : x ∈ baseSquareSpan (F := F) (K := K)) :
    ∃ g : Polynomial F,
      Polynomial.aeval pb.gen g = x ∧
        g ∈ boundedSquarePolynomialCone (F := F) pb.dim := by
  refine Submodule.span_induction (p := fun y _ =>
    ∃ g : Polynomial F,
      Polynomial.aeval pb.gen g = y ∧
        g ∈ boundedSquarePolynomialCone (F := F) pb.dim) ?_ ?_ ?_ ?_ hx
  · intro y hy
    change IsSquare y at hy
    rcases hy with ⟨z, hy⟩
    obtain ⟨g, hgdeg, hzg⟩ := pb.exists_eq_aeval z
    refine ⟨g * g, ?_, ?_⟩
    · rw [Polynomial.aeval_mul, ← hzg]
      exact hy.symm
    · apply Submodule.subset_span
      exact ⟨g, hgdeg, rfl⟩
  · refine ⟨0, by simp, ?_⟩
    exact (boundedSquarePolynomialCone (F := F) pb.dim).zero_mem
  · intro y z hy hz ihy ihz
    rcases ihy with ⟨g, hgeval, hg⟩
    rcases ihz with ⟨h, hheval, hh⟩
    refine ⟨g + h, ?_, ?_⟩
    · rw [Polynomial.aeval_add, hgeval, hheval]
    · exact (boundedSquarePolynomialCone (F := F) pb.dim).add_mem hg hh
  · intro a y hy ihy
    rcases ihy with ⟨g, hgeval, hg⟩
    refine ⟨a • g, ?_, ?_⟩
    · have h_eval : Polynomial.aeval pb.gen (a • g) =
          a • Polynomial.aeval pb.gen g := by
        change Polynomial.aeval pb.gen ((a : F) • g) =
          (a : F) • Polynomial.aeval pb.gen g
        rw [map_smul]
      rw [h_eval, hgeval]
    · exact (boundedSquarePolynomialCone (F := F) pb.dim).smul_mem a hg

end OrderedRealClosure
end RatFuncWittLocalGlobal
