/-
Copyright (c) 2026 Mocho Go. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Mocho Go
-/

import Hilbert17thProblem.RW.RealClosure.Odd.Basic
import Mathlib.Algebra.Ring.Subsemiring.Order

/-!
# A bounded polynomial square cone

The first bounded piece of the odd-orderability argument is a small cone of
polynomials generated by squares of bounded degree.  The scalars are the
nonnegative elements of the ordered coefficient field.  Consequently the
leading coefficient cannot cancel in an equal-degree sum, while every
generator has even degree and degree strictly below the doubled bound.
-/

namespace RatFuncWittLocalGlobal

open scoped _root_.Polynomial
open _root_.Polynomial

universe u

namespace OrderedRealClosure

variable {F : Type u} [Field F] [LinearOrder F] [IsStrictOrderedRing F]

/-! The generators and their nonnegative-scalar span. -/

/-- Squares of polynomials of natural degree strictly below `n`. -/
def oddPolynomialSquareGenerators (n : ℕ) : Set (Polynomial F) :=
  {p | ∃ g : Polynomial F, g.natDegree < n ∧ p = g * g}

/-- The bounded polynomial square cone, with nonnegative coefficients. -/
noncomputable def oddPolynomialCone (n : ℕ) : Submodule (Subsemiring.nonneg F) (Polynomial F) :=
  Submodule.span (Subsemiring.nonneg F) (oddPolynomialSquareGenerators n)

/-- Alias emphasizing the finite degree bound used by the orderability slice. -/
noncomputable def boundedSquarePolynomialCone (n : ℕ) :
    Submodule (Subsemiring.nonneg F) (Polynomial F) :=
  oddPolynomialCone n

namespace oddPolynomialCone

private abbrev Invariant (n : ℕ) (p : Polynomial F) : Prop :=
  0 ≤ p.leadingCoeff ∧ Even p.natDegree ∧ p.natDegree < 2 * n

omit [IsStrictOrderedRing F] in
private theorem invariant_zero (hn : 0 < n) : Invariant n (0 : Polynomial F) := by
  have hbound : 0 < 2 * n := Nat.mul_pos Nat.zero_lt_two hn
  exact ⟨by simp, Even.zero, by simpa using hbound⟩

private theorem invariant_generator {n : ℕ} (hn : 0 < n) {p : Polynomial F}
    (hp : p ∈ oddPolynomialSquareGenerators (F := F) n) : Invariant n p := by
  rcases hp with ⟨g, hg, rfl⟩
  by_cases hg0 : g = 0
  · subst g
    simpa using (invariant_zero (F := F) hn)
  · have hdegree : (g * g).natDegree = 2 * g.natDegree := by
      rw [natDegree_mul hg0 hg0]
      simp [two_mul]
    have hbound : (g * g).natDegree < 2 * n := by
      rw [hdegree]
      exact (Nat.mul_lt_mul_left Nat.zero_lt_two).2 hg
    refine ⟨?_, ?_, hbound⟩
    · rw [leadingCoeff_mul]
      exact mul_self_nonneg _
    · rw [hdegree]
      exact even_two_mul _

private theorem invariant_smul {n : ℕ} (hn : 0 < n) (a : Subsemiring.nonneg F)
    {p : Polynomial F} (hp : Invariant n p) : Invariant n (a • p) := by
  by_cases ha : a = 0
  · subst a
    simpa using invariant_zero hn
  by_cases hp0 : p = 0
  · subst p
    simpa using invariant_zero hn
  have haF : (a : F) ≠ 0 := by
    intro h
    apply ha
    exact Subtype.ext h
  have hdegree : (a • p).natDegree = p.natDegree := by
    rw [show a • p = (a : F) • p by rfl, smul_eq_C_mul]
    rw [natDegree_mul (by simp [haF]) hp0]
    simp
  have hlc : (a • p).leadingCoeff = (a : F) * p.leadingCoeff := by
    rw [show a • p = (a : F) • p by rfl, smul_eq_C_mul,
      leadingCoeff_mul, leadingCoeff_C]
  refine ⟨?_, ?_, ?_⟩
  · rw [hlc]
    exact mul_nonneg a.property hp.1
  · rw [hdegree]
    exact hp.2.1
  · rw [hdegree]
    exact hp.2.2

private theorem invariant_add {n : ℕ} {p q : Polynomial F}
    (hp : Invariant n p) (hq : Invariant n q) : Invariant n (p + q) := by
  by_cases hp0 : p = 0
  · subst p
    simpa using hq
  by_cases hq0 : q = 0
  · subst q
    simpa using hp
  by_cases hpq : p.natDegree < q.natDegree
  · have hdegree : (p + q).natDegree = q.natDegree :=
      natDegree_add_eq_right_of_natDegree_lt hpq
    have hlc : (p + q).leadingCoeff = q.leadingCoeff :=
      leadingCoeff_add_of_degree_lt (degree_lt_degree hpq)
    refine ⟨?_, ?_, ?_⟩
    · rw [hlc]
      exact hq.1
    · rw [hdegree]
      exact hq.2.1
    · rw [hdegree]
      exact hq.2.2
  by_cases hqp : q.natDegree < p.natDegree
  · have hdegree : (p + q).natDegree = p.natDegree :=
      natDegree_add_eq_left_of_natDegree_lt hqp
    have hlc : (p + q).leadingCoeff = p.leadingCoeff :=
      leadingCoeff_add_of_degree_lt' (degree_lt_degree hqp)
    refine ⟨?_, ?_, ?_⟩
    · rw [hlc]
      exact hp.1
    · rw [hdegree]
      exact hp.2.1
    · rw [hdegree]
      exact hp.2.2
  have hpqeq : p.natDegree = q.natDegree := by
    exact Nat.le_antisymm (Nat.le_of_not_gt hqp) (Nat.le_of_not_gt hpq)
  have hp_pos : 0 < p.leadingCoeff :=
    lt_of_le_of_ne hp.1 (Ne.symm (leadingCoeff_ne_zero.mpr hp0))
  have hq_pos : 0 < q.leadingCoeff :=
    lt_of_le_of_ne hq.1 (Ne.symm (leadingCoeff_ne_zero.mpr hq0))
  have hsum_pos : 0 < p.leadingCoeff + q.leadingCoeff := add_pos hp_pos hq_pos
  have hsum_ne : p.leadingCoeff + q.leadingCoeff ≠ 0 := ne_of_gt hsum_pos
  have hdeg : p.degree = q.degree := by
    rw [degree_eq_natDegree hp0, degree_eq_natDegree hq0, hpqeq]
  have hdegree : (p + q).natDegree = p.natDegree := by
    apply natDegree_eq_of_degree_eq
    rw [degree_add_eq_of_leadingCoeff_add_ne_zero hsum_ne, hdeg, max_self]
  have hlc : (p + q).leadingCoeff = p.leadingCoeff + q.leadingCoeff :=
    leadingCoeff_add_of_degree_eq hdeg hsum_ne
  refine ⟨?_, ?_, ?_⟩
  · rw [hlc]
    exact hsum_pos.le
  · rw [hdegree]
    exact hp.2.1
  · rw [hdegree]
    exact hp.2.2

/-! The public invariant API. -/

/-- Membership in the bounded square cone forces nonnegative leading coefficient,
even natural degree, and degree below twice the bound. -/
theorem invariant {n : ℕ} (hn : 0 < n) {p : Polynomial F}
    (hp : p ∈ oddPolynomialCone (F := F) n) :
    0 ≤ p.leadingCoeff ∧ Even p.natDegree ∧ p.natDegree < 2 * n := by
  refine Submodule.span_induction (p := fun q _ => Invariant n q) ?_ ?_ ?_ ?_ hp
  · intro q hq
    exact invariant_generator hn hq
  · exact invariant_zero hn
  · intro p q hp hq ihp ihq
    exact invariant_add ihp ihq
  · intro a p hp ihp
    exact invariant_smul hn a ihp

end oddPolynomialCone
end OrderedRealClosure
end RatFuncWittLocalGlobal
