/-
Copyright (c) 2026 Mocho Go. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Mocho Go
-/

import Hilbert17thProblem.RW.Ordering.Extension
import Hilbert17thProblem.RW.RealClosure.Odd.Lift

/-!
# The base-square subsemiring and additive square span

The ordered-closure construction uses the additive span of squares over the
nonnegative base scalars, while the maximal-preordering argument starts from
the subsemiring generated by the same elements.  This file records the small
bridge between the two presentations.
-/

namespace RatFuncWittLocalGlobal

namespace OrderedRealClosure

variable {F K : Type*} [Field F] [Field K] [Algebra F K]
  [LinearOrder F] [IsStrictOrderedRing F]

private theorem baseSquareSpan_mul_mem
    {x y : K}
    (hx : x ∈ baseSquareSpan (F := F) (K := K))
    (hy : y ∈ baseSquareSpan (F := F) (K := K)) :
    x * y ∈ baseSquareSpan (F := F) (K := K) := by
  refine Submodule.span_induction₂ (p := fun x y _ _ =>
    x * y ∈ baseSquareSpan (F := F) (K := K)) ?_ ?_ ?_ ?_ ?_ ?_ ?_ hx hy
  · intro x y hx hy
    rcases hx with ⟨u, rfl⟩
    rcases hy with ⟨v, rfl⟩
    apply Submodule.subset_span
    exact ⟨u * v, by ring⟩
  · intro y hy
    simp
  · intro x hx
    simp
  · intro x y z hx hy hz hxy hxz
    rw [add_mul]
    exact (baseSquareSpan (F := F) (K := K)).add_mem hxy hxz
  · intro x y z hx hy hz hxy hxz
    rw [mul_add]
    exact (baseSquareSpan (F := F) (K := K)).add_mem hxy hxz
  · intro a x y hx hy hxy
    rw [smul_mul_assoc]
    exact (baseSquareSpan (F := F) (K := K)).smul_mem a hxy
  · intro a x y hx hy hxy
    rw [mul_smul_comm]
    exact (baseSquareSpan (F := F) (K := K)).smul_mem a hxy

theorem baseSquareSubsemiring_le_baseSquareSpan :
    (RingPreordering.baseSquareSubsemiring (F := F) (K := K) : Set K) ⊆
      (baseSquareSpan (F := F) (K := K) : Set K) := by
  intro x hx
  induction hx using Subsemiring.closure_induction with
  | mem z hz =>
      rcases hz with ⟨a, ha, rfl⟩ | ⟨y, rfl⟩
      · have hmem :=
          (baseSquareSpan (F := F) (K := K)).smul_mem
            (⟨a, ha⟩ : Subsemiring.nonneg F)
            (show (1 : K) ∈ baseSquareSpan (F := F) (K := K) by
              apply Submodule.subset_span
              exact (show IsSquare (1 : K) from ⟨1, by simp⟩))
        have hmap :
            algebraMap (Subsemiring.nonneg F) K ⟨a, ha⟩ = algebraMap F K a := by
          change algebraMap (Subsemiring.nonneg F) K ⟨a, ha⟩ =
            algebraMap F K (algebraMap (Subsemiring.nonneg F) F ⟨a, ha⟩)
          exact
            (IsScalarTower.algebraMap_apply (Subsemiring.nonneg F) F K ⟨a, ha⟩).symm
        rw [Algebra.smul_def, mul_one, hmap] at hmem
        exact hmem
      · apply Submodule.subset_span
        exact ⟨y, rfl⟩
  | zero => exact (baseSquareSpan (F := F) (K := K)).zero_mem
  | one =>
      apply Submodule.subset_span
      exact (show IsSquare (1 : K) from ⟨1, by simp⟩)
  | add x y hx hy hxs hys =>
      exact (baseSquareSpan (F := F) (K := K)).add_mem hxs hys
  | mul x y hx hy hxs hys =>
      exact baseSquareSpan_mul_mem hxs hys

/-- A proper additive base-square span yields an ordered algebra extension. -/
theorem exists_orderedAlgebraExtension_of_baseSquareSpanProper
    (hproper : (-1 : K) ∉ baseSquareSpan (F := F) (K := K)) :
    ∃ (O : _root_.RingPreordering K) (hO : O.IsOrdering),
      (∀ a : F, 0 ≤ a →
        @LE.le K
          (@RatFuncWittLocalGlobal.RingPreordering.linearOrderOfIsOrdering K _ O hO).toLE
          0 (algebraMap F K a)) ∧
      (∀ a : F, 0 < a →
        @LT.lt K
          (@RatFuncWittLocalGlobal.RingPreordering.linearOrderOfIsOrdering K _ O hO).toLT
          0 (algebraMap F K a)) := by
  apply _root_.RingPreordering.exists_orderedAlgebraExtension_of_baseSquareSubsemiring
  intro hneg
  exact hproper (baseSquareSubsemiring_le_baseSquareSpan hneg)

end OrderedRealClosure
end RatFuncWittLocalGlobal
